import type { Product, PriceHistory, PriceListing, PlatformId } from './types'
import { subDays } from 'date-fns'

function genHistory(base: number, days = 30): PriceHistory[] {
  const history: PriceHistory[] = []
  for (let i = days; i >= 0; i--) {
    const variance = () => base * (0.85 + Math.random() * 0.25)
    history.push({
      date: subDays(new Date(), i),
      prices: {
        tokopedia:  i % 7 === 0 ? null : Math.round(variance() / 1000) * 1000,
        shopee:     Math.round(variance() * 0.94 / 1000) * 1000,
        lazada:     Math.round(variance() * 1.02 / 1000) * 1000,
        bukalapak:  i > 20 ? null : Math.round(variance() * 0.97 / 1000) * 1000,
        blibli:     Math.round(variance() * 1.05 / 1000) * 1000,
        tiktok:     i > 15 ? null : Math.round(variance() * 0.91 / 1000) * 1000,
        amazon:     null,
        alibaba:    null,
        aliexpress: null,
        jd:         null,
      },
    })
  }
  return history
}

function listing(
  platformId: PlatformId,
  price: number,
  opts: Partial<PriceListing> = {}
): PriceListing {
  const origMultiplier = 1 + (Math.random() * 0.3)
  const originalPrice = Math.round(price * origMultiplier / 1000) * 1000
  return {
    platformId,
    price,
    originalPrice,
    discount: Math.round(((originalPrice - price) / originalPrice) * 100),
    rating: 4.2 + Math.random() * 0.7,
    reviewCount: Math.floor(100 + Math.random() * 5000),
    sold: Math.floor(50 + Math.random() * 10000),
    stock: Math.floor(10 + Math.random() * 200),
    shopName: `Toko ${platformId.charAt(0).toUpperCase()}${platformId.slice(1)} Official`,
    shopVerified: Math.random() > 0.3,
    freeShipping: Math.random() > 0.4,
    url: `https://${platformId === 'tokopedia' ? 'tokopedia.com' : platformId === 'shopee' ? 'shopee.co.id' : platformId + '.co.id'}/product/mock-${platformId}`,
    affiliateUrl: `https://harga.app/go/${platformId}/mock-product`,
    imageUrl: `https://picsum.photos/seed/${platformId}/400/400`,
    updatedAt: new Date(),
    ...opts,
  }
}

export const MOCK_PRODUCTS: Product[] = [
  // ── SMARTPHONES ──────────────────────────────────────────────────────────
  {
    id: 'iphone-15-pro-max-256',
    name: 'Apple iPhone 15 Pro Max 256GB Natural Titanium',
    slug: 'apple-iphone-15-pro-max-256gb',
    brand: 'Apple',
    category: 'Elektronik',
    subcategory: 'Smartphone',
    description: 'iPhone 15 Pro Max hadir dengan chip A17 Pro, kamera 48MP dengan lensa telephoto 5x, layar Super Retina XDR 6.7 inci, dan bodi titanium premium.',
    specifications: {
      'Layar': '6.7" Super Retina XDR OLED',
      'Prosesor': 'Apple A17 Pro',
      'RAM': '8 GB',
      'Storage': '256 GB',
      'Kamera Utama': '48 MP + 12 MP + 12 MP',
      'Kamera Depan': '12 MP TrueDepth',
      'Baterai': '4422 mAh',
      'OS': 'iOS 17',
      'Konektivitas': '5G, WiFi 6E, Bluetooth 5.3',
      'Warna': 'Natural Titanium',
    },
    images: [
      'https://picsum.photos/seed/iphone15pm/600/600',
      'https://picsum.photos/seed/iphone15pm2/600/600',
      'https://picsum.photos/seed/iphone15pm3/600/600',
    ],
    tags: ['iphone', 'apple', 'smartphone', '5g', 'titanium'],
    listings: [
      listing('tokopedia',  19299000, { shopName: 'iBox Official Store', shopVerified: true }),
      listing('shopee',     18799000, { shopName: 'Apple Authorized', shopVerified: true }),
      listing('lazada',     19499000, { shopName: 'Lazada Official', shopVerified: true }),
      listing('bukalapak',  19100000, { shopName: 'BL Mall Apple', shopVerified: true }),
      listing('blibli',     19599000, { shopName: 'Blibli Apple Store', shopVerified: true }),
      listing('tiktok',     18599000, { shopName: 'TikTok Flash Sale', shopVerified: false }),
      listing('olx',        13500000, { shopName: 'JualBeliHP_Jaksel', shopVerified: false, condition: 'used' }),
      listing('carousell',  14200000, { shopName: 'GadgetBekas', shopVerified: false, condition: 'used' }),
    ],
    priceHistory: genHistory(19000000),
    lowestPrice: 13500000,
    highestPrice: 19599000,
    averageRating: 4.8,
    totalReviews: 12847,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'samsung-s24-ultra-256',
    name: 'Samsung Galaxy S24 Ultra 256GB Titanium Black',
    slug: 'samsung-galaxy-s24-ultra-256gb',
    brand: 'Samsung',
    category: 'Elektronik',
    subcategory: 'Smartphone',
    description: 'Galaxy S24 Ultra dengan AI Galaxy, S Pen terintegrasi, kamera 200MP, dan layar Dynamic AMOLED 2X 6.8 inci.',
    specifications: {
      'Layar': '6.8" Dynamic AMOLED 2X',
      'Prosesor': 'Snapdragon 8 Gen 3',
      'RAM': '12 GB',
      'Storage': '256 GB',
      'Kamera Utama': '200 MP + 12 MP + 10 MP + 50 MP',
      'Baterai': '5000 mAh',
      'OS': 'Android 14 / One UI 6.1',
      'Fitur': 'S Pen, Galaxy AI, IP68',
    },
    images: ['https://picsum.photos/seed/s24ultra/600/600'],
    tags: ['samsung', 'galaxy', 's24', 'spen', 'android'],
    listings: [
      listing('tokopedia',  16799000, { shopName: 'Samsung Official', shopVerified: true }),
      listing('shopee',     16299000, { shopName: 'Samsung Store ID', shopVerified: true }),
      listing('lazada',     16999000, { shopName: 'Samsung Lazada', shopVerified: true }),
      listing('blibli',     17099000),
      listing('tiktok',     15999000, { discount: 15 }),
      listing('olx',        11500000, { shopName: 'HP_Bekas_Bandung', shopVerified: false, condition: 'used' }),
      listing('carousell',  12200000, { shopName: 'ElektroBekas', shopVerified: false, condition: 'used' }),
    ],
    priceHistory: genHistory(16500000),
    lowestPrice: 11500000,
    highestPrice: 17099000,
    averageRating: 4.7,
    totalReviews: 8432,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'xiaomi-14-ultra-512',
    name: 'Xiaomi 14 Ultra 512GB Titanium White',
    slug: 'xiaomi-14-ultra-512gb',
    brand: 'Xiaomi',
    category: 'Elektronik',
    subcategory: 'Smartphone',
    description: 'Xiaomi 14 Ultra menggabungkan sistem kamera Leica terbaik dengan chip Snapdragon 8 Gen 3 dan layar LTPO AMOLED 6.73 inci.',
    specifications: {
      'Layar': '6.73" LTPO AMOLED, 120Hz',
      'Prosesor': 'Snapdragon 8 Gen 3',
      'RAM': '16 GB',
      'Storage': '512 GB',
      'Kamera': 'Leica 50MP Quad Camera',
      'Baterai': '5000 mAh, 90W Wired + 80W Wireless',
      'OS': 'Android 14 / HyperOS',
      'IP Rating': 'IP68',
    },
    images: ['https://picsum.photos/seed/xiaomi14u/600/600'],
    tags: ['xiaomi', '14 ultra', 'leica', 'smartphone', 'flagship'],
    listings: [
      listing('tokopedia',  13499000, { shopName: 'Xiaomi Official Store', shopVerified: true }),
      listing('shopee',     12999000, { shopName: 'Mi Store ID', shopVerified: true }),
      listing('lazada',     13699000, { shopName: 'Xiaomi Lazada', shopVerified: true }),
      listing('tiktok',     12799000, { shopName: 'Xiaomi Flash Sale', shopVerified: true }),
      listing('blibli',     13899000),
      listing('olx',        8900000, { shopName: 'XiaomiBekas_Surabaya', shopVerified: false, condition: 'used' }),
    ],
    priceHistory: genHistory(13200000),
    lowestPrice: 8900000,
    highestPrice: 13899000,
    averageRating: 4.7,
    totalReviews: 5612,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'samsung-galaxy-a55-256',
    name: 'Samsung Galaxy A55 5G 256GB Awesome Iceblue',
    slug: 'samsung-galaxy-a55-5g-256gb',
    brand: 'Samsung',
    category: 'Elektronik',
    subcategory: 'Smartphone',
    description: 'Samsung Galaxy A55 5G dengan desain premium, kamera 50MP OIS, Exynos 1480, dan layar Super AMOLED 6.6 inci dengan proteksi Gorilla Glass Victus+.',
    specifications: {
      'Layar': '6.6" Super AMOLED, 120Hz',
      'Prosesor': 'Exynos 1480',
      'RAM': '8 GB',
      'Storage': '256 GB',
      'Kamera': '50MP + 12MP + 5MP',
      'Baterai': '5000 mAh, 25W Charging',
      'OS': 'Android 14 / One UI 6.1',
    },
    images: ['https://picsum.photos/seed/samsungA55/600/600'],
    tags: ['samsung', 'galaxy a55', '5g', 'midrange', 'android'],
    listings: [
      listing('tokopedia',  5299000, { shopName: 'Samsung Official', shopVerified: true }),
      listing('shopee',     4999000, { shopName: 'Samsung Store ID', shopVerified: true }),
      listing('lazada',     5399000),
      listing('bukalapak',  5199000),
      listing('blibli',     5499000),
      listing('tiktok',     4899000, { discount: 12 }),
    ],
    priceHistory: genHistory(5100000),
    lowestPrice: 4899000,
    highestPrice: 5499000,
    averageRating: 4.5,
    totalReviews: 9841,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'oppo-reno-11-pro-256',
    name: 'OPPO Reno 11 Pro 5G 256GB Rock Grey',
    slug: 'oppo-reno-11-pro-5g-256gb',
    brand: 'OPPO',
    category: 'Elektronik',
    subcategory: 'Smartphone',
    description: 'OPPO Reno 11 Pro 5G dengan desain lensa kamera besar, Dimensity 8200, kamera portrait 50MP, dan layar AMOLED 6.74 inci yang memukau.',
    specifications: {
      'Layar': '6.74" AMOLED, 120Hz',
      'Prosesor': 'MediaTek Dimensity 8200',
      'RAM': '12 GB',
      'Storage': '256 GB',
      'Kamera': '50MP + 32MP Telephoto + 8MP',
      'Baterai': '4600 mAh, 80W SUPERVOOC',
      'OS': 'Android 14 / ColorOS 14',
    },
    images: ['https://picsum.photos/seed/opporeno11/600/600'],
    tags: ['oppo', 'reno 11', '5g', 'portrait', 'android'],
    listings: [
      listing('tokopedia',  7299000, { shopName: 'OPPO Official Store', shopVerified: true }),
      listing('shopee',     6999000, { shopName: 'OPPO Store Indonesia', shopVerified: true }),
      listing('lazada',     7499000),
      listing('tiktok',     6799000, { discount: 10 }),
      listing('blibli',     7599000),
    ],
    priceHistory: genHistory(7100000),
    lowestPrice: 6799000,
    highestPrice: 7599000,
    averageRating: 4.4,
    totalReviews: 4203,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── LAPTOPS ──────────────────────────────────────────────────────────────
  {
    id: 'macbook-pro-m3-14',
    name: 'Apple MacBook Pro 14" M3 Pro 18GB 512GB Space Black',
    slug: 'apple-macbook-pro-14-m3-pro',
    brand: 'Apple',
    category: 'Elektronik',
    subcategory: 'Laptop',
    description: 'MacBook Pro 14" dengan chip M3 Pro, layar Liquid Retina XDR, baterai 18 jam, dan performa yang luar biasa untuk profesional kreatif.',
    specifications: {
      'Layar': '14.2" Liquid Retina XDR',
      'Chip': 'Apple M3 Pro',
      'CPU': '11-core',
      'GPU': '14-core',
      'RAM': '18 GB',
      'Storage': '512 GB SSD',
      'Baterai': 'Hingga 18 jam',
    },
    images: ['https://picsum.photos/seed/macm3/600/600'],
    tags: ['macbook', 'apple', 'laptop', 'm3', 'pro'],
    listings: [
      listing('tokopedia',  29999000, { shopName: 'iBox Official', shopVerified: true }),
      listing('shopee',     29499000, { shopName: 'Apple Auth Reseller', shopVerified: true }),
      listing('lazada',     30299000),
      listing('blibli',     30499000),
    ],
    priceHistory: genHistory(30000000),
    lowestPrice: 29499000,
    highestPrice: 30499000,
    averageRating: 4.9,
    totalReviews: 3291,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'asus-rog-zephyrus-g14',
    name: 'ASUS ROG Zephyrus G14 2024 AMD Ryzen 9 RTX 4060',
    slug: 'asus-rog-zephyrus-g14-2024',
    brand: 'ASUS',
    category: 'Elektronik',
    subcategory: 'Laptop Gaming',
    description: 'ROG Zephyrus G14 2024 dengan panel OLED 3K 120Hz, Ryzen 9 8945HS, RTX 4060, dan desain ultra-slim yang ikonik dengan AniMe Matrix LED.',
    specifications: {
      'Layar': '14" OLED 3K 120Hz',
      'Prosesor': 'AMD Ryzen 9 8945HS',
      'GPU': 'NVIDIA RTX 4060',
      'RAM': '16 GB DDR5',
      'Storage': '1 TB NVMe SSD',
      'Baterai': '73Whr, 100W Charging',
      'OS': 'Windows 11',
      'Berat': '1.65 kg',
    },
    images: ['https://picsum.photos/seed/rogzeph/600/600'],
    tags: ['asus', 'rog', 'gaming', 'laptop', 'rtx 4060', 'amd'],
    listings: [
      listing('tokopedia',  22999000, { shopName: 'ASUS Official Store', shopVerified: true }),
      listing('shopee',     21999000, { shopName: 'ROG Store ID', shopVerified: true }),
      listing('lazada',     23499000),
      listing('blibli',     23999000),
      listing('tiktok',     21499000, { discount: 8 }),
    ],
    priceHistory: genHistory(22500000),
    lowestPrice: 21499000,
    highestPrice: 23999000,
    averageRating: 4.7,
    totalReviews: 2108,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lenovo-thinkpad-x1-carbon',
    name: 'Lenovo ThinkPad X1 Carbon Gen 12 Intel Core Ultra 7',
    slug: 'lenovo-thinkpad-x1-carbon-gen12',
    brand: 'Lenovo',
    category: 'Elektronik',
    subcategory: 'Laptop',
    description: 'ThinkPad X1 Carbon Gen 12 — laptop bisnis paling legendaris dengan Intel Core Ultra 7, layar IPS 2K, dan bobot hanya 1.12 kg.',
    specifications: {
      'Layar': '14" IPS 2.8K 120Hz',
      'Prosesor': 'Intel Core Ultra 7 165U',
      'RAM': '16 GB LPDDR5',
      'Storage': '512 GB SSD',
      'Baterai': '57Whr, hingga 15 jam',
      'OS': 'Windows 11 Pro',
      'Berat': '1.12 kg',
      'IP Rating': 'MIL-STD-810H',
    },
    images: ['https://picsum.photos/seed/thinkpadx1/600/600'],
    tags: ['lenovo', 'thinkpad', 'bisnis', 'laptop', 'intel', 'ultra slim'],
    listings: [
      listing('tokopedia',  25999000, { shopName: 'Lenovo Official Store', shopVerified: true }),
      listing('shopee',     24999000, { shopName: 'Lenovo Indonesia', shopVerified: true }),
      listing('lazada',     26499000),
      listing('blibli',     26999000),
    ],
    priceHistory: genHistory(26000000),
    lowestPrice: 24999000,
    highestPrice: 26999000,
    averageRating: 4.8,
    totalReviews: 987,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── TABLETS ──────────────────────────────────────────────────────────────
  {
    id: 'ipad-pro-m4-11-256',
    name: 'Apple iPad Pro 11" M4 256GB WiFi Space Black',
    slug: 'apple-ipad-pro-11-m4-256gb',
    brand: 'Apple',
    category: 'Elektronik',
    subcategory: 'Tablet',
    description: 'iPad Pro terbaru dengan chip M4, layar Ultra Retina XDR OLED tandem, desain tertipis yang pernah ada, dan Apple Pencil Pro.',
    specifications: {
      'Layar': '11" Ultra Retina XDR OLED',
      'Chip': 'Apple M4',
      'RAM': '8 GB',
      'Storage': '256 GB',
      'Kamera': '12MP Wide + 10MP Ultra Wide',
      'Baterai': 'Hingga 10 jam',
      'Konektivitas': 'WiFi 6E, Bluetooth 5.3',
    },
    images: ['https://picsum.photos/seed/ipadprom4/600/600'],
    tags: ['ipad', 'apple', 'tablet', 'm4', 'pro', 'oled'],
    listings: [
      listing('tokopedia',  17499000, { shopName: 'iBox Official', shopVerified: true }),
      listing('shopee',     16999000, { shopName: 'Apple Authorized', shopVerified: true }),
      listing('lazada',     17799000),
      listing('blibli',     17999000),
    ],
    priceHistory: genHistory(17200000),
    lowestPrice: 16999000,
    highestPrice: 17999000,
    averageRating: 4.9,
    totalReviews: 2403,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'samsung-galaxy-tab-s9-256',
    name: 'Samsung Galaxy Tab S9 256GB WiFi Graphite + S Pen',
    slug: 'samsung-galaxy-tab-s9-256gb',
    brand: 'Samsung',
    category: 'Elektronik',
    subcategory: 'Tablet',
    description: 'Galaxy Tab S9 dengan layar Dynamic AMOLED 2X 11 inci, Snapdragon 8 Gen 2, IP68 waterproof, dan S Pen terintegrasi.',
    specifications: {
      'Layar': '11" Dynamic AMOLED 2X, 120Hz',
      'Prosesor': 'Snapdragon 8 Gen 2',
      'RAM': '8 GB',
      'Storage': '256 GB',
      'Kamera Belakang': '13 MP + 6 MP',
      'Baterai': '8400 mAh',
      'IP Rating': 'IP68',
      'S Pen': 'Termasuk dalam paket',
    },
    images: ['https://picsum.photos/seed/galtabs9/600/600'],
    tags: ['samsung', 'galaxy tab', 'tablet', 's pen', 'android'],
    listings: [
      listing('tokopedia',  11999000, { shopName: 'Samsung Official', shopVerified: true }),
      listing('shopee',     11499000, { shopName: 'Samsung Store ID', shopVerified: true }),
      listing('lazada',     12299000),
      listing('blibli',     12499000),
      listing('tiktok',     11199000, { discount: 9 }),
    ],
    priceHistory: genHistory(11800000),
    lowestPrice: 11199000,
    highestPrice: 12499000,
    averageRating: 4.7,
    totalReviews: 3876,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── AUDIO & ACCESSORIES ──────────────────────────────────────────────────
  {
    id: 'sony-wh1000xm5',
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    slug: 'sony-wh-1000xm5-headphones',
    brand: 'Sony',
    category: 'Elektronik',
    subcategory: 'Headphone',
    description: 'WH-1000XM5 dengan teknologi noise cancelling terdepan industri, kualitas suara Hi-Res Audio, mikrofon untuk panggilan jernih, dan baterai 30 jam.',
    specifications: {
      'Driver': '30mm',
      'Noise Cancelling': 'Industry-leading ANC',
      'Baterai': 'Hingga 30 jam (ANC on)',
      'Charging': 'USB-C, 3 min = 3 jam',
      'Codec': 'LDAC, AAC, SBC',
      'Konektivitas': 'Bluetooth 5.2, multipoint',
    },
    images: ['https://picsum.photos/seed/sonywh1000/600/600'],
    tags: ['sony', 'headphone', 'noise cancelling', 'wireless', 'anc'],
    listings: [
      listing('tokopedia',  4299000, { shopName: 'Sony Official Store', shopVerified: true }),
      listing('shopee',     3999000, { shopName: 'Sony Store ID', shopVerified: true }),
      listing('lazada',     4499000),
      listing('blibli',     4599000),
      listing('tiktok',     3799000, { discount: 15 }),
    ],
    priceHistory: genHistory(4100000),
    lowestPrice: 3799000,
    highestPrice: 4599000,
    averageRating: 4.8,
    totalReviews: 18934,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'jbl-flip-6',
    name: 'JBL Flip 6 Portable Bluetooth Speaker Squad',
    slug: 'jbl-flip-6-bluetooth-speaker',
    brand: 'JBL',
    category: 'Elektronik',
    subcategory: 'Speaker',
    description: 'JBL Flip 6 dengan suara bold & punchy, IP67 waterproof & dustproof, baterai 12 jam, dan PartyBoost untuk gabungkan speaker.',
    specifications: {
      'Output': '30W RMS',
      'Baterai': '12 jam',
      'IP Rating': 'IP67',
      'Bluetooth': '5.1',
      'Fitur': 'PartyBoost, JBL App',
      'Ukuran': '178 x 68 x 68 mm',
    },
    images: ['https://picsum.photos/seed/jblflip6/600/600'],
    tags: ['jbl', 'speaker', 'bluetooth', 'waterproof', 'portable'],
    listings: [
      listing('tokopedia',  1299000, { shopName: 'JBL Official Store', shopVerified: true }),
      listing('shopee',     1199000, { shopName: 'JBL Indonesia', shopVerified: true }),
      listing('lazada',     1349000),
      listing('bukalapak',  1249000),
      listing('blibli',     1399000),
      listing('tiktok',     1149000, { discount: 18 }),
    ],
    priceHistory: genHistory(1250000),
    lowestPrice: 1149000,
    highestPrice: 1399000,
    averageRating: 4.7,
    totalReviews: 24701,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── GAMING ───────────────────────────────────────────────────────────────
  {
    id: 'ps5-slim-disc',
    name: 'Sony PlayStation 5 Slim Disc Edition',
    slug: 'sony-ps5-slim-disc-edition',
    brand: 'Sony',
    category: 'Gaming',
    subcategory: 'Konsol',
    description: 'PS5 Slim lebih ramping 30% dari PS5 original, dengan SSD custom 1TB, DualSense wireless controller, dan pengalaman gaming 4K.',
    specifications: {
      'CPU': 'AMD Zen 2, 3.5 GHz',
      'GPU': 'AMD RDNA 2, 10.3 TFLOPS',
      'Storage': '1 TB SSD',
      'RAM': '16 GB GDDR6',
      'Resolusi': 'Hingga 8K',
      'Frame Rate': 'Hingga 120fps',
    },
    images: ['https://picsum.photos/seed/ps5slim/600/600'],
    tags: ['ps5', 'playstation', 'sony', 'gaming', 'konsol'],
    listings: [
      listing('tokopedia',  7999000, { shopName: 'Sony Official', shopVerified: true }),
      listing('shopee',     7799000, { shopName: 'Sony Store ID', shopVerified: true }),
      listing('lazada',     8099000),
      listing('blibli',     8199000),
    ],
    priceHistory: genHistory(8000000),
    lowestPrice: 7799000,
    highestPrice: 8199000,
    averageRating: 4.9,
    totalReviews: 6721,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'nintendo-switch-oled',
    name: 'Nintendo Switch OLED Model White',
    slug: 'nintendo-switch-oled-white',
    brand: 'Nintendo',
    category: 'Gaming',
    subcategory: 'Konsol',
    description: 'Nintendo Switch OLED dengan layar OLED 7 inci yang lebih terang dan tajam, stand adjustable lebar, port LAN terpasang, dan memori internal 64GB.',
    specifications: {
      'Layar': '7" OLED',
      'Storage': '64 GB',
      'Baterai': '4.5 - 9 jam',
      'Konektivitas': 'WiFi, Bluetooth, LAN (dock)',
      'Mode': 'TV, Tabletop, Handheld',
    },
    images: ['https://picsum.photos/seed/switcholed/600/600'],
    tags: ['nintendo', 'switch', 'oled', 'gaming', 'portable'],
    listings: [
      listing('tokopedia',  3799000, { shopName: 'Nintendo Official ID', shopVerified: true }),
      listing('shopee',     3699000, { shopName: 'Nintendo Store', shopVerified: true }),
      listing('lazada',     3899000),
      listing('bukalapak',  3749000),
      listing('blibli',     3999000),
      listing('tiktok',     3599000, { discount: 10 }),
    ],
    priceHistory: genHistory(3750000),
    lowestPrice: 3599000,
    highestPrice: 3999000,
    averageRating: 4.8,
    totalReviews: 11243,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── SMART DEVICES ────────────────────────────────────────────────────────
  {
    id: 'samsung-galaxy-watch6-classic-47',
    name: 'Samsung Galaxy Watch 6 Classic 47mm Black Stainless',
    slug: 'samsung-galaxy-watch6-classic-47mm',
    brand: 'Samsung',
    category: 'Elektronik',
    subcategory: 'Smartwatch',
    description: 'Galaxy Watch 6 Classic dengan bezel putar ikonik, monitor kesehatan canggih (ECG, tekanan darah, sleep tracking), Wear OS by Samsung.',
    specifications: {
      'Layar': '1.4" Super AMOLED',
      'Prosesor': 'Exynos W930 Dual Core',
      'Storage': '16 GB',
      'Baterai': '425 mAh',
      'Sensor': 'BioActive, Accelerometer, Gyro, Barometer',
      'IP Rating': 'IP68, MIL-STD-810H',
    },
    images: ['https://picsum.photos/seed/gwatch6/600/600'],
    tags: ['samsung', 'galaxy watch', 'smartwatch', 'ecg', 'wearable'],
    listings: [
      listing('tokopedia',  4999000, { shopName: 'Samsung Official', shopVerified: true }),
      listing('shopee',     4699000, { shopName: 'Samsung Store ID', shopVerified: true }),
      listing('lazada',     5199000),
      listing('blibli',     5299000),
      listing('tiktok',     4499000, { discount: 12 }),
    ],
    priceHistory: genHistory(4800000),
    lowestPrice: 4499000,
    highestPrice: 5299000,
    averageRating: 4.6,
    totalReviews: 7823,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── HOME APPLIANCES ──────────────────────────────────────────────────────
  {
    id: 'dyson-v15-detect',
    name: 'Dyson V15 Detect Absolute Cordless Vacuum',
    slug: 'dyson-v15-detect-absolute',
    brand: 'Dyson',
    category: 'Rumah Tangga',
    subcategory: 'Vacuum Cleaner',
    description: 'Vacuum cordless Dyson V15 Detect dengan laser yang mendeteksi debu halus, sensor akustik piezo, dan suction 230AW.',
    specifications: {
      'Daya Hisap': '230 AW',
      'Kapasitas': '0.76L',
      'Baterai': 'Hingga 60 menit',
      'Teknologi': 'Laser Slim Fluffy, Piezo sensor',
    },
    images: ['https://picsum.photos/seed/dysonv15/600/600'],
    tags: ['dyson', 'vacuum', 'cordless', 'rumah tangga'],
    listings: [
      listing('tokopedia',  8999000, { shopName: 'Dyson Official', shopVerified: true }),
      listing('shopee',     8699000, { shopName: 'Dyson ID Official', shopVerified: true }),
      listing('lazada',     9199000),
      listing('blibli',     9299000),
      listing('tiktok',     8499000),
    ],
    priceHistory: genHistory(9000000),
    lowestPrice: 8499000,
    highestPrice: 9299000,
    averageRating: 4.6,
    totalReviews: 2847,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'dyson-airwrap-complete',
    name: 'Dyson Airwrap Complete Long Hair Styler Nickel/Copper',
    slug: 'dyson-airwrap-complete-long',
    brand: 'Dyson',
    category: 'Kecantikan',
    subcategory: 'Alat Rambut',
    description: 'Dyson Airwrap Complete Long dengan teknologi Coanda effect, curl + wave + smooth tanpa panas ekstrem, dilengkapi attachment lengkap untuk semua jenis rambut.',
    specifications: {
      'Teknologi': 'Coanda effect airflow',
      'Kecepatan Angin': '3 pengaturan',
      'Suhu': '3 pengaturan + cold shot',
      'Tegangan': '220-240V',
      'Attachment': '8 buah',
    },
    images: ['https://picsum.photos/seed/dysonair/600/600'],
    tags: ['dyson', 'airwrap', 'rambut', 'styling', 'kecantikan'],
    listings: [
      listing('tokopedia',  8199000, { shopName: 'Dyson Beauty Official', shopVerified: true }),
      listing('shopee',     7899000, { shopName: 'Dyson ID Official', shopVerified: true }),
      listing('lazada',     8499000),
      listing('blibli',     8699000),
      listing('tiktok',     7699000, { discount: 8 }),
    ],
    priceHistory: genHistory(8100000),
    lowestPrice: 7699000,
    highestPrice: 8699000,
    averageRating: 4.7,
    totalReviews: 6104,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lg-27gp850-monitor',
    name: 'LG 27GP850-B UltraGear 27" QHD 165Hz IPS Gaming Monitor',
    slug: 'lg-27gp850-gaming-monitor',
    brand: 'LG',
    category: 'Elektronik',
    subcategory: 'Monitor',
    description: 'LG UltraGear 27GP850-B dengan panel Nano IPS, resolusi QHD 2560x1440, 165Hz (1ms GtG), NVIDIA G-Sync Compatible, HDR 400.',
    specifications: {
      'Layar': '27" Nano IPS',
      'Resolusi': '2560 x 1440 (QHD)',
      'Refresh Rate': '165Hz (OC 180Hz)',
      'Response Time': '1ms GtG',
      'HDR': 'VESA DisplayHDR 400',
      'Konektivitas': 'HDMI 2.0 x2, DP 1.4, USB-A Hub',
    },
    images: ['https://picsum.photos/seed/lgmonitor/600/600'],
    tags: ['lg', 'monitor', 'gaming', 'qhd', '165hz', 'nano ips'],
    listings: [
      listing('tokopedia',  5799000, { shopName: 'LG Official Store', shopVerified: true }),
      listing('shopee',     5499000, { shopName: 'LG Indonesia', shopVerified: true }),
      listing('lazada',     5999000),
      listing('blibli',     6199000),
      listing('tiktok',     5399000, { discount: 11 }),
    ],
    priceHistory: genHistory(5700000),
    lowestPrice: 5399000,
    highestPrice: 6199000,
    averageRating: 4.7,
    totalReviews: 4512,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── FASHION ──────────────────────────────────────────────────────────────
  {
    id: 'nike-air-max-270',
    name: 'Nike Air Max 270 React Mens Running Shoes',
    slug: 'nike-air-max-270-react-mens',
    brand: 'Nike',
    category: 'Fashion',
    subcategory: 'Sepatu Olahraga',
    description: 'Nike Air Max 270 React dengan unit Air terbesar dalam sejarah sneaker Nike, memberikan kenyamanan dan gaya maksimal.',
    specifications: {
      'Material Upper': 'Engineered mesh',
      'Sole': 'React foam + Air Max 270',
      'Tinggi': 'Low-top',
      'Kegunaan': 'Lifestyle / Casual',
    },
    images: ['https://picsum.photos/seed/nikeam270/600/600'],
    tags: ['nike', 'air max', 'sepatu', 'running', 'olahraga'],
    listings: [
      listing('tokopedia',  1899000, { shopName: 'Nike Official', shopVerified: true }),
      listing('shopee',     1799000),
      listing('lazada',     1949000),
      listing('bukalapak',  1849000),
      listing('blibli',     1999000),
      listing('tiktok',     1699000, { discount: 20 }),
    ],
    priceHistory: genHistory(1900000),
    lowestPrice: 1699000,
    highestPrice: 1999000,
    averageRating: 4.5,
    totalReviews: 15632,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'adidas-ultraboost-22',
    name: 'Adidas Ultraboost 22 Core Black Running Shoes',
    slug: 'adidas-ultraboost-22-core-black',
    brand: 'Adidas',
    category: 'Fashion',
    subcategory: 'Sepatu Olahraga',
    description: 'Adidas Ultraboost 22 dengan teknologi Boost terbaru, material Primeknit+ yang memeluk kaki, dan Torsion System untuk stabilitas optimal saat berlari.',
    specifications: {
      'Material': 'Primeknit+',
      'Midsole': 'Boost + Linear Energy Push',
      'Outsole': 'Continental™ Rubber',
      'Kegunaan': 'Running / Lifestyle',
    },
    images: ['https://picsum.photos/seed/adidasub22/600/600'],
    tags: ['adidas', 'ultraboost', 'sepatu', 'lari', 'running', 'boost'],
    listings: [
      listing('tokopedia',  2099000, { shopName: 'Adidas Official Store', shopVerified: true }),
      listing('shopee',     1949000, { shopName: 'adidas Indonesia', shopVerified: true }),
      listing('lazada',     2199000),
      listing('bukalapak',  1999000),
      listing('blibli',     2299000),
      listing('tiktok',     1899000, { discount: 15 }),
    ],
    priceHistory: genHistory(2050000),
    lowestPrice: 1899000,
    highestPrice: 2299000,
    averageRating: 4.6,
    totalReviews: 9874,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'uniqlo-ultralight-down',
    name: 'Uniqlo Ultra Light Down Compact Jacket Olive',
    slug: 'uniqlo-ultra-light-down-jacket',
    brand: 'Uniqlo',
    category: 'Fashion',
    subcategory: 'Jaket',
    description: 'Jaket Uniqlo Ultra Light Down yang bisa dilipat menjadi saku kecil, menggunakan bulu bebek 90% untuk insulasi hangat yang ringan, tersedia dalam berbagai warna.',
    specifications: {
      'Material': '100% Nylon / 90% Bulu Bebek Down',
      'Berat': '~200g',
      'Fitur': 'Packable into pocket',
      'Care': 'Machine washable',
    },
    images: ['https://picsum.photos/seed/uniqlodown/600/600'],
    tags: ['uniqlo', 'jaket', 'down', 'packable', 'fashion', 'musim dingin'],
    listings: [
      listing('tokopedia',   599000, { shopName: 'Uniqlo Official', shopVerified: true }),
      listing('shopee',      549000, { shopName: 'UNIQLO Indonesia', shopVerified: true }),
      listing('lazada',      619000),
      listing('bukalapak',   579000),
      listing('blibli',      629000),
      listing('tiktok',      529000, { discount: 14 }),
    ],
    priceHistory: genHistory(580000),
    lowestPrice: 529000,
    highestPrice: 629000,
    averageRating: 4.5,
    totalReviews: 31204,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── KAMERA ───────────────────────────────────────────────────────────────
  {
    id: 'fujifilm-instax-mini-12',
    name: 'Fujifilm Instax Mini 12 Instant Camera Pastel Blue',
    slug: 'fujifilm-instax-mini-12-pastel-blue',
    brand: 'Fujifilm',
    category: 'Elektronik',
    subcategory: 'Kamera Instan',
    description: 'Instax Mini 12 dengan desain yang lebih compact, mode Close-Up baru untuk selfie jarak dekat, mode Auto Exposure, dan tampilan yang cute & colorful.',
    specifications: {
      'Jenis': 'Kamera Instan',
      'Film': 'Instax Mini',
      'Ukuran Foto': '54mm x 86mm',
      'Exposure Control': 'Otomatis',
      'Flash': 'Built-in Auto',
      'Baterai': '2x AA',
    },
    images: ['https://picsum.photos/seed/instaxmini12/600/600'],
    tags: ['fujifilm', 'instax', 'kamera instan', 'polaroid', 'foto'],
    listings: [
      listing('tokopedia',   899000, { shopName: 'Fujifilm Official', shopVerified: true }),
      listing('shopee',      849000, { shopName: 'Fujifilm Indonesia', shopVerified: true }),
      listing('lazada',      929000),
      listing('bukalapak',   879000),
      listing('blibli',      949000),
      listing('tiktok',      819000, { discount: 13 }),
    ],
    priceHistory: genHistory(880000),
    lowestPrice: 819000,
    highestPrice: 949000,
    averageRating: 4.6,
    totalReviews: 22187,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // ── BARANG BEKAS (OLX / Carousell) ──────────────────────────────────────
  {
    id: 'macbook-pro-m1-bekas',
    name: 'MacBook Pro M1 13in 8GB/256GB Mulus Like New',
    slug: 'macbook-pro-m1-bekas',
    brand: 'Apple',
    category: 'Elektronik',
    subcategory: 'Laptop',
    description: 'MacBook Pro M1 kondisi mulus seperti baru. Baterai 96%, lengkap dus charger.',
    specifications: { 'Chip': 'Apple M1', 'RAM': '8 GB', 'Storage': '256 GB SSD', 'Kondisi': 'Bekas Like New' },
    images: ['https://picsum.photos/seed/mbp-m1-used/600/600'],
    tags: ['macbook', 'apple', 'laptop', 'bekas', 'm1'],
    listings: [
      listing('olx',       9500000, { shopName: 'AppleCollector_JKT', shopVerified: false, condition: 'used' }),
      listing('carousell', 10200000, { shopName: 'LaptopMulus', shopVerified: false, condition: 'used' }),
    ],
    priceHistory: genHistory(9500000),
    lowestPrice: 9500000,
    highestPrice: 10200000,
    averageRating: 4.5,
    totalReviews: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'sony-wh1000xm4-bekas',
    name: 'Sony WH-1000XM4 Bekas Kondisi 95%',
    slug: 'sony-wh1000xm4-bekas',
    brand: 'Sony',
    category: 'Elektronik',
    subcategory: 'Audio',
    description: 'Sony WH-1000XM4 bekas 6 bulan. Semua aksesoris lengkap, ANC berfungsi sempurna.',
    specifications: { 'Type': 'Over-ear ANC', 'Konektivitas': 'Bluetooth 5.0', 'Baterai': '30 jam', 'Kondisi': 'Bekas 95%' },
    images: ['https://picsum.photos/seed/xm4-used/600/600'],
    tags: ['sony', 'headphone', 'bekas', 'anc', 'xm4'],
    listings: [
      listing('olx',       1850000, { shopName: 'AudioBekas_Bdg', shopVerified: false, condition: 'used' }),
      listing('carousell', 2100000, { shopName: 'GadgetSeken', shopVerified: false, condition: 'used' }),
    ],
    priceHistory: genHistory(1850000),
    lowestPrice: 1850000,
    highestPrice: 2100000,
    averageRating: 4.6,
    totalReviews: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ps5-digital-bekas',
    name: 'PlayStation 5 Digital Edition Bekas Lengkap',
    slug: 'ps5-digital-edition-bekas',
    brand: 'Sony',
    category: 'Gaming',
    subcategory: 'Console',
    description: 'PS5 Digital Edition bekas 2023. Kondisi baik, lengkap box, kabel, controller.',
    specifications: { 'Storage': '825 GB SSD', 'Output': '4K 120fps', 'Kondisi': 'Bekas Baik' },
    images: ['https://picsum.photos/seed/ps5-used/600/600'],
    tags: ['ps5', 'playstation', 'gaming', 'bekas', 'console'],
    listings: [
      listing('olx',       5800000, { shopName: 'GamersHub_SBY', shopVerified: false, condition: 'used' }),
      listing('carousell', 6200000, { shopName: 'KonsoleBekas', shopVerified: false, condition: 'used' }),
    ],
    priceHistory: genHistory(5800000),
    lowestPrice: 5800000,
    highestPrice: 6200000,
    averageRating: 4.7,
    totalReviews: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ipad-pro-m2-bekas',
    name: 'iPad Pro M2 11in 128GB WiFi Fullset Mulus',
    slug: 'ipad-pro-m2-bekas',
    brand: 'Apple',
    category: 'Elektronik',
    subcategory: 'Tablet',
    description: 'iPad Pro M2 11 inci, 128GB, bekas 8 bulan. Baterai 99%, fullset original, mulus.',
    specifications: { 'Chip': 'Apple M2', 'Storage': '128 GB', 'Kondisi': 'Bekas Mulus' },
    images: ['https://picsum.photos/seed/ipad-pro-m2-used/600/600'],
    tags: ['ipad', 'apple', 'tablet', 'bekas', 'm2'],
    listings: [
      listing('olx',       8200000, { shopName: 'TabletPro_JKT', shopVerified: false, condition: 'used' }),
      listing('carousell', 8700000, { shopName: 'iPadBekas', shopVerified: false, condition: 'used' }),
    ],
    priceHistory: genHistory(8200000),
    lowestPrice: 8200000,
    highestPrice: 8700000,
    averageRating: 4.8,
    totalReviews: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ── MOBIL BEKAS ──────────────────────────────────────────────────────────────
  {
    id: 'toyota-avanza-2020-bekas',
    name: 'Toyota Avanza 1.3 G 2020 Manual Silver',
    slug: 'toyota-avanza-2020-manual-silver-olx',
    brand: 'Toyota',
    category: 'Mobil Bekas',
    subcategory: 'MPV',
    description: 'Toyota Avanza 1.3 G tahun 2020, transmisi manual, warna silver metalik. Kondisi sangat baik, km 45.000, lengkap dokumen.',
    specifications: {
      'Merek': 'Toyota', 'Model': 'Avanza', 'Tahun': '2020',
      'Transmisi': 'Manual', 'Warna': 'Silver', 'Kilometer': '45.000 km',
      'Bahan Bakar': 'Bensin', 'Kondisi': 'Bekas Baik',
    },
    images: ['/placeholder-product.png'],
    tags: ['toyota', 'avanza', 'mpv', 'mobil bekas', 'manual', '2020'],
    listings: [
      listing('olx', 155000000, { shopName: 'MobilBekas_JKT', shopVerified: false, condition: 'used' }),
    ],
    priceHistory: genHistory(155000000),
    lowestPrice: 155000000,
    highestPrice: 155000000,
    averageRating: 4.3,
    totalReviews: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'honda-brio-2022-bekas',
    name: 'Honda Brio RS CVT 2022 Putih Istimewa',
    slug: 'honda-brio-rs-cvt-2022-putih-olx',
    brand: 'Honda',
    category: 'Mobil Bekas',
    subcategory: 'Hatchback',
    description: 'Honda Brio RS CVT 2022, warna putih, km 18.000. Kondisi istimewa, ban baru, kamera belakang.',
    specifications: {
      'Merek': 'Honda', 'Model': 'Brio RS', 'Tahun': '2022',
      'Transmisi': 'CVT', 'Warna': 'Putih', 'Kilometer': '18.000 km',
      'Bahan Bakar': 'Bensin', 'Kondisi': 'Istimewa',
    },
    images: ['/placeholder-product.png'],
    tags: ['honda', 'brio', 'rs', 'cvt', 'mobil bekas', '2022'],
    listings: [
      listing('olx', 178000000, { shopName: 'Honda_Seken_BDG', shopVerified: false, condition: 'used' }),
      listing('carousell', 182000000, { shopName: 'MobilMulus', shopVerified: false, condition: 'used' }),
    ],
    priceHistory: genHistory(178000000),
    lowestPrice: 178000000,
    highestPrice: 182000000,
    averageRating: 4.6,
    totalReviews: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'daihatsu-xenia-2019-bekas',
    name: 'Daihatsu Xenia 1.3 X Deluxe 2019 Hitam Manual',
    slug: 'daihatsu-xenia-2019-hitam-olx',
    brand: 'Daihatsu',
    category: 'Mobil Bekas',
    subcategory: 'MPV',
    description: 'Daihatsu Xenia 1.3 X Deluxe 2019, warna hitam, transmisi manual. Km 67.000, pajak panjang.',
    specifications: {
      'Merek': 'Daihatsu', 'Model': 'Xenia X Deluxe', 'Tahun': '2019',
      'Transmisi': 'Manual', 'Warna': 'Hitam', 'Kilometer': '67.000 km',
      'Kondisi': 'Bekas Baik',
    },
    images: ['/placeholder-product.png'],
    tags: ['daihatsu', 'xenia', 'mpv', 'mobil bekas', '2019'],
    listings: [
      listing('olx', 128000000, { shopName: 'JualMobil_SBY', shopVerified: false, condition: 'used' }),
    ],
    priceHistory: genHistory(128000000),
    lowestPrice: 128000000,
    highestPrice: 128000000,
    averageRating: 4.1,
    totalReviews: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'suzuki-ertiga-2021-bekas',
    name: 'Suzuki Ertiga GX AT 2021 Merah Low KM',
    slug: 'suzuki-ertiga-2021-merah-olx',
    brand: 'Suzuki',
    category: 'Mobil Bekas',
    subcategory: 'MPV',
    description: 'Suzuki Ertiga GX AT 2021, warna merah, km hanya 22.000. Kondisi prima, servis rutin di dealer.',
    specifications: {
      'Merek': 'Suzuki', 'Model': 'Ertiga GX', 'Tahun': '2021',
      'Transmisi': 'Otomatis', 'Warna': 'Merah', 'Kilometer': '22.000 km',
      'Kondisi': 'Sangat Baik',
    },
    images: ['/placeholder-product.png'],
    tags: ['suzuki', 'ertiga', 'mpv', 'mobil bekas', '2021', 'low km'],
    listings: [
      listing('olx', 198000000, { shopName: 'SuzukiBekas_JKT', shopVerified: true, condition: 'used' }),
      listing('carousell', 205000000, { shopName: 'MobilKeren', shopVerified: false, condition: 'used' }),
    ],
    priceHistory: genHistory(198000000),
    lowestPrice: 198000000,
    highestPrice: 205000000,
    averageRating: 4.7,
    totalReviews: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export function searchProducts(query: string, filters?: {
  category?: string
  minPrice?: number
  maxPrice?: number
}): Product[] {
  let results = MOCK_PRODUCTS

  if (filters?.category) {
    results = results.filter(p =>
      p.category.toLowerCase() === filters.category!.toLowerCase() ||
      p.subcategory.toLowerCase().includes(filters.category!.toLowerCase())
    )
  }

  if (query.trim()) {
    const q = query.toLowerCase()
    results = results.filter(p =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.tags.some(t => t.includes(q)) ||
      p.category.toLowerCase().includes(q) ||
      p.subcategory.toLowerCase().includes(q)
    )
  }

  if (filters?.minPrice) {
    results = results.filter(p => p.lowestPrice >= filters.minPrice!)
  }
  if (filters?.maxPrice) {
    results = results.filter(p => p.lowestPrice <= filters.maxPrice!)
  }

  return results
}

export function getProductById(id: string): Product | undefined {
  return MOCK_PRODUCTS.find(p => p.id === id || p.slug === id)
}

export const TRENDING_SEARCHES = [
  'iPhone 15 Pro Max',
  'Samsung Galaxy S24',
  'MacBook Pro M3',
  'Dyson V15',
  'PS5 Slim',
  'Nintendo Switch OLED',
  'Nike Air Max',
  'AirPods Pro',
  'iPad Pro M4',
  'Sony WH-1000XM5',
  'ASUS ROG',
  'Xiaomi 14 Ultra',
]

export const CATEGORIES = [
  { id: 'elektronik',  label: 'Elektronik',   icon: '📱', count: 124500 },
  { id: 'fashion',     label: 'Fashion',       icon: '👟', count: 89200  },
  { id: 'rumah-tangga',label: 'Rumah Tangga',  icon: '🏠', count: 67800  },
  { id: 'gaming',      label: 'Gaming',        icon: '🎮', count: 45300  },
  { id: 'kecantikan',  label: 'Kecantikan',    icon: '💄', count: 98700  },
  { id: 'olahraga',    label: 'Olahraga',      icon: '⚽', count: 56200  },
  { id: 'motor-bekas', label: 'Motor Bekas',   icon: '🏍️', count: 84     },
  { id: 'mobil-bekas', label: 'Mobil Bekas',   icon: '🚙', count: 101    },
]

export const STATS = {
  totalProducts: '2.400',
  platforms: 17,
  updateInterval: '4 Jam',
  totalUsers: '128K',
  cashbackPaid: 'Rp 2.3 M',
}

// Items untuk live ticker
export const LIVE_TICKER_ITEMS = [
  { icon: '📱', name: 'iPhone 15 Pro Max', platform: 'Shopee', price: 18799000, change: -2.3 },
  { icon: '💻', name: 'MacBook Pro M3', platform: 'Tokopedia', price: 29999000, change: 0 },
  { icon: '🎮', name: 'PS5 Slim', platform: 'Shopee', price: 7799000, change: -1.2 },
  { icon: '👟', name: 'Nike Air Max 270', platform: 'TikTok', price: 1699000, change: -5.5 },
  { icon: '🎧', name: 'Sony WH-1000XM5', platform: 'TikTok', price: 3799000, change: -7.2 },
  { icon: '📱', name: 'Samsung S24 Ultra', platform: 'TikTok', price: 15999000, change: -4.1 },
  { icon: '🎮', name: 'Nintendo Switch OLED', platform: 'TikTok', price: 3599000, change: -4.7 },
  { icon: '💻', name: 'ASUS ROG Zephyrus G14', platform: 'TikTok', price: 21499000, change: -4.4 },
  { icon: '📷', name: 'Instax Mini 12', platform: 'TikTok', price: 819000, change: -6.8 },
  { icon: '👕', name: 'Uniqlo Light Down Jacket', platform: 'TikTok', price: 529000, change: -8.9 },
  { icon: '📱', name: 'Xiaomi 14 Ultra', platform: 'TikTok', price: 12799000, change: -2.9 },
]
